### PR TITLE
Adding sub-Issues pages

### PR DESCRIPTION
**Pull request by HTumey**
Adding content components for individual sub-issues: Climate, Russia,
Planned Parenthood, and Healthcare

### CODE REVIEW

**Comment by tyrw** [comment]
Looks good -- are these all the changes for now, or are there more on the way?

**Comment by HTumey** [comment]
One more quick one on index page. To link to the blog (Medium) is this the correct link? 
I was a little confused by the content question on this: https://medium.com/fight-for-better <https://medium.com/fight-for-better>

Thanks,Heather

**Comment by tyrw** [comment]
Yes that is correct

**Comment by HTumey** [comment]
Great, this is ready to go.

**Comment by tyrw** [comment]
@HTumey I haven't seen a change come through since you said one more thing -- did you push it?

**Comment by HTumey** [comment]
@tyrw GIT didn't see it for some reason. See it now? 
https://github.com/F4ABA/website/pull/2/commits/4f6d27bf1f76dadab15fc52d64622b5c77cf6a03

**Comment by tyrw** [comment]
Looks great, thanks!

**Pull request merged**
